name: Julia

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # label used to access the service container
      minio:
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000
        env:
          MINIO_DOMAIN: localhost
      postgres:
        # docker hub image
        image: postgres
        # provide the password for postgres
        env:
          POSTGRES_PASSWORD: rFcLGNkgsNtksg6Pgtn9CumL4xXBQ7
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
      colonies:
        image: colonyos/colonies:v1.8.7
        env:
            LANG: en_US.UTF-8
            LANGUAGE: en_US.UTF-8
            LC_ALL: en_US.UTF-8
            LC_CTYPE: UTF-8
            TZ: Europe/Stockholm
            COLONIES_SERVER_TLS: false
            COLONIES_SERVER_HOST: localhost
            COLONIES_SERVER_PORT: 50080
            COLONIES_MONITOR_PORT: 21120
            COLONIES_MONITOR_INTERVAL: 1
            COLONIES_SERVER_ID: 039231c7644e04b6895471dd5335cf332681c54e27f81fac54f9067b3f2c0103
            COLONIES_SERVER_PRVKEY: fcc79953d8a751bf41db661592dc34d30004b1a651ffa0725b03ac227641499d
            COLONIES_DB_HOST: postgres
            COLONIES_DB_USER: postgres
            COLONIES_DB_PORT: 5432
            COLONIES_DB_PASSWORD: rFcLGNkgsNtksg6Pgtn9CumL4xXBQ7
            COLONIES_COLONY_NAME: test
            COLONIES_COLONY_ID: 4787a5071856a4acf702b2ffcea422e3237a679c681314113d86139461290cf4
            COLONIES_COLONY_PRVKEY: ba949fa134981372d6da62b6a56f336ab4d843b22c02a4257dcf7d0d73097514
            COLONIES_EXECUTOR_ID: 3fc05cf3df4b494e95d6a3d297a34f19938f7daa7422ab0d4f794454133341ac
            COLONIES_PRVKEY: ddf7f7791208083b6a9ed975a72684f6406a269cfa36f1b1c32045c0a71fff05
            COLONIES_EXECUTOR_TYPE: cli
            COLONIES_CRON_CHECKER_PERIOD: 1000
            COLONIES_GENERATOR_CHECKER_PERIOD: 1000
            COLONIES_EXCLUSIVE_ASSIGN: true
            COLONIES_INITDB: true
        ports:
          - 50080:50080
        options: >-
          --health-cmd "colonies server alive"
          --health-interval 1s
          --health-timeout 60s
          --health-retries 20
    steps:
    - uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1

    - name: Test
      env:
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: en_US.UTF-8
        LC_CTYPE: UTF-8
        TZ: Europe/Stockholm
        COLONIES_SERVER_TLS: false
        COLONIES_DB_HOST: localhost
        COLONIES_DB_USER: postgres
        COLONIES_DB_PORT: 5432
        COLONIES_DB_PASSWORD: rFcLGNkgsNtksg6Pgtn9CumL4xXBQ7
        COLONIES_SERVER_HOST: localhost
        COLONIES_SERVER_PORT: 50080
        COLONIES_SERVER_ID: 039231c7644e04b6895471dd5335cf332681c54e27f81fac54f9067b3f2c0103
        COLONIES_SERVER_PRVKEY: fcc79953d8a751bf41db661592dc34d30004b1a651ffa0725b03ac227641499d
        COLONIES_COLONY_NAME: test
        COLONIES_COLONY_ID: 4787a5071856a4acf702b2ffcea422e3237a679c681314113d86139461290cf4
        COLONIES_COLONY_PRVKEY: ba949fa134981372d6da62b6a56f336ab4d843b22c02a4257dcf7d0d73097514
        COLONIES_EXECUTOR_ID: 3fc05cf3df4b494e95d6a3d297a34f19938f7daa7422ab0d4f794454133341ac
        COLONIES_PRVKEY: ddf7f7791208083b6a9ed975a72684f6406a269cfa36f1b1c32045c0a71fff05
        COLONIES_EXECUTOR_NAME: cli
        COLONIES_EXECUTOR_TYPE: cli
        CRYPTOLIB: /home/runner/work/pycolonies/pycolonies/lib/libcryptolib.so
        CFSLIB: /home/runner/work/pycolonies/pycolonies/lib/libcfslib.so
        AWS_S3_ENDPOINT: localhost:9000
        AWS_S3_ACCESSKEY: minioadmin
        AWS_S3_SECRETKEY: minioadmin
        AWS_S3_TLS: false
        AWS_S3_SKIPVERIFY: false
        AWS_S3_BUCKET: test
      run: make github_test 
